apiVersion: package-operator.run/v1alpha1
kind: Package
metadata:
  name: demo
spec:
  image: quay.io/app-sre/unleash-pko:a13bc3d
  config:
    unleash:
      host: host
      authz:
        clientId: foo
        clientSecret: bar
        host: https://my-keykloak/auth
        realm: realm
      sessionSecret: foo
      accessTokens:
        admin: foor
        client: bar
    db:
      host: postgresql
      port: 5432
      user: demo
      password: demo
      name: demo
      ssl: false
