version: "3.8"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
    - "4242:4242"
    environment:
      DATABASE_HOST: "db"
      DATABASE_PORT: "5432"
      DATABASE_USERNAME: "postgres"
      DATABASE_PASSWORD: "password"
      DATABASE_NAME: "postgres"
      DATABASE_SSL: "false"
      KC_HOST: "http://host.docker.internal:8080"
      KC_REALM: "unleash"
      KC_CLIENT_ID: "unleash"
      KC_ADMIN_ROLES: "admin"
      KC_EDITOR_ROLES: "editor"
      KC_VIEWER_ROLES: "viewer"
    env_file:
    - .env
    depends_on:
    - db
    - keycloak
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "password"
    expose:
    - "5432"
  keycloak:
    image: quay.io/keycloak/keycloak:22.0.5
    command: start-dev --import-realm
    ports:
    - "8080:8080"
    environment:
      KEYCLOAK_ADMIN: "admin"
      KEYCLOAK_ADMIN_PASSWORD: "admin"
    volumes:
    - ./keycloak_data:/opt/keycloak/data/import
