FROM registry.access.redhat.com/ubi9/ubi-minimal:9.8-1791279563@sha256:5ed244b62bbf4095080144d9d35eb8fcd3d39a9801f94aadd63b9d10978a01ae AS base
COPY LICENSE /licenses/LICENSE


FROM base AS downloader
ENV K6_VERSION=0.47.0
RUN microdnf install -y tar gzip && \
    mkdir -p /tmp/k6 && \
    curl -sfL https://github.com/grafana/k6/releases/download/v${K6_VERSION}/k6-v${K6_VERSION}-linux-amd64.tar.gz \
    | tar -zxf - -C /tmp/k6 --strip-components=1 && \
    chmod +x /tmp/k6/k6 && \
    microdnf clean all


FROM base AS integration
COPY --from=downloader /tmp/k6/k6 /usr/local/bin/k6
COPY integration_test/test.js /test.js
CMD ["k6","run", "/test.js"]
