---
apiVersion: v1
kind: Template
metadata:
  name: ${identifier}
objects:
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    name: unleash
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    labels:
      app: ${identifier}
    name: ${identifier}
  spec:
    replicas: ${{REPLICAS}}
    strategy:
      type: RollingUpdate
      rollingUpdate:
        maxUnavailable: 0
        maxSurge: 1
    selector:
      matchLabels:
        app: ${identifier}
    template:
      metadata:
        labels:
          app: ${identifier}
      spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - unleash
              topologyKey: "kubernetes.io/hostname"
            weight: 100
        containers:
        - image: ${IMAGE}:${IMAGE_TAG}
          imagePullPolicy: Always
          name: ${identifier}
          env:
            - name: ORG
              value: ${org}
            - name: TEAM
              value: ${team}
            - name: DATABASE_HOST
              valueFrom:
                 secretKeyRef:
                   name: ${databaseSecret}
                   key: db.host
            - name: DATABASE_PORT
              valueFrom:
                 secretKeyRef:
                   name: ${databaseSecret}
                   key: db.port
            - name: DATABASE_USERNAME
              valueFrom:
                 secretKeyRef:
                   name: ${databaseSecret}
                   key: db.user
            - name: DATABASE_PASSWORD
              valueFrom:
                 secretKeyRef:
                   name: ${databaseSecret}
                   key: db.password
            - name: DATABASE_NAME
              valueFrom:
                secretKeyRef:
                  name: ${databaseSecret}
                  key: db.name
            - name: GH_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: ${configSecret}
                  key: GH_CLIENT_ID
            - name: GH_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: ${configSecret}
                  key: GH_CLIENT_SECRET
            - name: GH_CALLBACK_URL
              valueFrom:
                secretKeyRef:
                  name: ${configSecret}
                  key: GH_CALLBACK_URL
            - name: ADMIN_ACCESS_TOKEN
              valueFrom:
                secretKeyRef:
                  name: ${configSecret}
                  key: ADMIN_ACCESS_TOKEN
            - name: SESSION_SECRET
              valueFrom:
                secretKeyRef:
                  name: ${configSecret}
                  key: SESSION_SECRET
            - name: CLIENT_ACCESS_TOKEN
              valueFrom:
                secretKeyRef:
                  name: ${tokenSecret}
                  key: CLIENT_ACCESS_TOKEN
          ports:
          - name: unleash
            containerPort: 4242
          resources:
            requests:
              memory: ${MEMORY_REQUESTS}
              cpu: ${CPU_REQUESTS}
            limits:
              memory: ${MEMORY_LIMIT}
              cpu: ${CPU_LIMIT}
          readinessProbe:
            failureThreshold: 3
            initialDelaySeconds: 5
            periodSeconds: 10
            successThreshold: 1
            tcpSocket:
              port: 4242
            timeoutSeconds: 1
          livenessProbe:
            failureThreshold: 3
            initialDelaySeconds: 5
            periodSeconds: 10
            successThreshold: 1
            tcpSocket:
              port: 4242
            timeoutSeconds: 1
- apiVersion: v1
  kind: Service
  metadata:
    name: ${identifier}
    labels:
      app: ${identifier}
  spec:
    ports:
      - protocol: TCP
        port: 80
        targetPort: 4242
        name: ${identifier}
    selector:
      app: ${identifier}

parameters:
- name: IMAGE
  value: quay.io/app-sre/unleash
  displayName: unleash image
  description: unleash docker image. Defaults to quay.io/app-sre/unleash
- name: IMAGE_TAG
  value: latest
  displayName: unleash version
  description: unleash version which defaults to latest
- name: REPLICAS
  value: "3"
- name: MEMORY_REQUESTS
  value: 100Mi
- name: MEMORY_LIMIT
  value: 200Mi
- name: CPU_REQUESTS
  value: 50m
- name: CPU_LIMIT
  value: 100m
- name: identifier
  value: app-interface
- name: configSecret
  value: app-interface-config
- name: databaseSecret
  value: app-interface-unleash-rds
- name: tokenSecret
  value: app-interface-token
- name: org
  value: app-sre
- name: team
  value: app-sre-cluster
